"""The hero invoice fixture is the designed document, and stays that way.

INV-1048.pdf is NOT generated by scripts/build_demo_invoice_fixture.py -- it is a
designed, checked-in PDF so that every path that can ever serve the hero (a fresh
operator_import, the acceptance scripts, a clean redeploy, the retained S3 copy)
serves the same document the camera sees. It drifted once: the pretty PDF was
uploaded to live S3 only, and the repo kept the plain generated one, so any
re-import silently produced the ugly invoice.

These tests assert the CLAIM FACTS (which the pipeline extracts) rather than one
layout's exact phrasing, so the document can be redesigned without breaking the
suite -- and separately assert that the hero is still the designed document, so a
revert to the generated one fails here instead of on camera.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pdfplumber

FIXTURE_DIR = Path(__file__).parents[1] / "fixtures" / "demo"

# The generated fixtures are ~1.2KB of raw text-drawing commands. The designed
# hero carries embedded fonts and is two orders of magnitude larger; this is the
# cheapest signal that distinguishes "designed" from "regenerated".
GENERATED_PDF_CEILING_BYTES = 10_000

# sha256 of the designed hero as retained in live S3 and recorded in the
# invoice_sources row the deployed demo serves.
RETAINED_HERO_SHA256 = (
    "31ffc2a7e8223f5144c32e35c802182f82f45691703f98506e5b9413ddce5550"
)


def _hero_text() -> str:
    with pdfplumber.open(FIXTURE_DIR / "INV-1048.pdf") as pdf:
        assert len(pdf.pages) == 1
        return pdf.pages[0].extract_text()


def _normalized(text: str) -> str:
    """Collapse whitespace so assertions survive line wrapping in the layout."""
    return re.sub(r"\s+", " ", text)


def test_representative_invoice_is_a_real_text_pdf_matching_expected_claims():
    pdf_path = FIXTURE_DIR / "INV-1048.pdf"
    expected = json.loads(
        (FIXTURE_DIR / "INV-1048.expected-claims.json").read_text()
    )

    assert pdf_path.read_bytes().startswith(b"%PDF-")
    with pdfplumber.open(pdf_path) as pdf:
        words = pdf.pages[0].extract_words()
    text = _normalized(_hero_text())

    # Extractable text, not a scan: the intake pipeline reads this with pdfplumber.
    assert len(words) > 20

    assert expected["invoice_number"] in text
    assert expected["container_number"] in text
    assert expected["bill_of_lading"] in text
    assert expected["charge_type"].capitalize() in text

    # The money and the window, layout-independent. $350/day x 7 = $2,450 is what
    # makes the hero's DISPUTE $700 (vs the $250 tariff) arithmetic true.
    assert "$350.00" in text
    assert "$2,450.00" in text
    assert "7 days" in text or "Charged Days: 7" in text
    assert "June 8, 2026" in text
    assert "June 14, 2026" in text
    assert "June 22, 2026" in text

    # Never ships without saying it is fictional.
    assert "FICTIONAL" in text.upper()


def test_hero_fixture_is_the_designed_pdf_not_the_generated_one():
    """Fails if INV-1048.pdf is ever regenerated over the designed document."""
    size = (FIXTURE_DIR / "INV-1048.pdf").stat().st_size
    assert size > GENERATED_PDF_CEILING_BYTES, (
        f"INV-1048.pdf is {size} bytes -- that is the generated placeholder, not "
        "the designed hero invoice. The hero is a checked-in designed PDF; "
        "scripts/build_demo_invoice_fixture.py must not write it."
    )


def test_hero_fixture_matches_the_bytes_retained_in_live_s3():
    """The repo fixture IS the retained artifact, byte for byte.

    This sha256 is the value recorded in the live invoice_sources row for
    INV-1048 (s3 key isolated-intake-v1/4b21bf70-.../invoice.pdf). Repo, S3
    object, and DB record are the same document -- if this fails, the fixture
    has drifted from what the demo actually serves, which is the exact bug this
    file exists to prevent.
    """
    digest = hashlib.sha256((FIXTURE_DIR / "INV-1048.pdf").read_bytes()).hexdigest()
    assert digest == RETAINED_HERO_SHA256


def test_fixture_builder_refuses_to_generate_the_hero():
    """The generator must not be able to clobber the designed hero."""
    import scripts.build_demo_invoice_fixture as builder

    generated = {spec.filename for spec in (builder.INV_1041, builder.INV_1050)}
    assert builder.HERO_FILENAME not in generated
